plugins {
    id 'java'
    id 'net.neoforged.moddev' version '2.0.107'
}

group = 'com.bdm'
version = '1.0.0'

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

neoForge {
    version = project.neoForgeVersion
}

repositories {
    mavenCentral()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
